% TXT2DATA
% ------------------------------------------------------------------------
% Takes all text files in a directory (presumably of spectroscopic data), 
% and read them into one data structure/dataset.
% ------------------------------------------------------------------------
% Developed for textfiles generated by Marq Metrix Raman system.
%
%
% Input:
%   directory - str, Path/directory for the textfiles that should be
%               merged. No other textfiles may be present
% Output:
%   spec_data - struct, Data from txt files merged in a matrix with Raman
%               shift/wavelength data and sample names.
%
% Required toolboxes: none
%
%
% Author: Tiril Aurora Lintvedt
% Nofima, Raw materials and process optimisation
% email address: tiril.lintvedt@nofima.no
% Website: 
% May 2020; Last revision: -
% MATLAB version: R2018b
% OS: Windows 10.0


function  spec_data = txt2data(directory)

% Allocate memory for spectral data, in saisir-like structure.
spec_data.i = []; % sample names
spec_data.rshift = []; % Raman shift
spec_data.wl = []; % Wavelength
spec_data.d = []; % Intensity/counts

textfiles_in_directory = dir('*.txt');  % MUST BE UPDATED TO GIVEN INPUT DIRETORY

for sample = 1:length(textfiles_in_directory)
    sample_id = textfiles_in_directory(sample).name;
    spectrum = readtable([directory,'/',sample_id]); 
    
    spec_data.i{sample,1} = sample_id(1:end-4) ;
    spec_data.rshift = spectrum.RamanShift ;
    spec_data.wl = spectrum.Wavelength ;
    spec_data.d(sample,:) = spectrum.RawCounts' ;
end

end